apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: ravidalal/customerservice:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/application.yaml
          subPath: application.yaml
      volumes:
      - name: config-volume
        configMap:
          name: customer-service-yaml
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    name: url
    targetPort: 8080
    protocol: TCP
  selector:
    app: customer-service
  type: LoadBalancer