apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: ravidalal/customerservice:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/app/cs/
      volumes:
      - name: config-volume
        configMap:
          name: customer-service-cm
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: default
spec:
  ports:
  - port: 80
    name: url
    targetPort: 8080
    protocol: TCP
  selector:
    app: customer-service
  type: LoadBalancer